#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1999-2014
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
################################################################################

# Script to configure this project

dlcincludepath="-I. -I$DLXPROJSRC -I$DLXPROJSRC/hist_dist_map/ \
-I$UXLIDEC/src/gems/actors/basic \
-I$UXLIDEC/src/gems/actors/common -I$UXLIDEC/src/gems/edges/basic \
-I$UXLIDEC/src/tools/runtime"
dlclibs="$DLXPROJSRC/lib_c_user_defined_actors.a \
$LIDECGEN/lide_c_actors_basic.a $LIDECGEN/lide_c_edges_basic.a \
$LIDECGEN/lide_c_runtime.a"
dlctargetfile="lide_c_objtr_hist_dist_map_driver.exe"
dlcinstalldir=""
dlcobjs="lide_c_objtr_hist_dist_map_driver.o"
dlcverbose=""
